#backend_extra:
# resource: .
# type: backend_extra
 
admin_plugins_carousel_index:
  path: /admin/plugins/carousel
  controller: Sputnik\CarouselBundle\Controller\Backend\GeneralController::index

#blog_list:
#  path: /blog/list/{page}
#  controller: App\Sputnik\DevBundle\Controller\Frontend\GeneralController::blogList
#  defaults:
#    page: 1
#  requirements:
#      parameter: \d+

