<?php
namespace Sputnik\CarouselBundle\DependencyInjection;

use Symfony\Component\DependencyInjection\ContainerBuilder;
use Symfony\Component\DependencyInjection\Extension\Extension;
use Symfony\Component\Config\FileLocator;
use Symfony\Component\DependencyInjection\Extension\PrependExtensionInterface;
use Symfony\Component\DependencyInjection\Loader\XmlFileLoader;

class CarouselExtension extends Extension implements PrependExtensionInterface
{

    /**
     * @param ContainerBuilder $container
     */
    public function prepend(ContainerBuilder $container)
    {
        #$config = Yaml::parse(file_get_contents(__DIR__.'/../Resources/config/routes.yaml'));
        #foreach ($config as $key => $configuration) {
        #    $container->prependExtensionConfig($key, $configuration);
        #}
    }

    public function getAlias()
    {
        return parent::getAlias(); // TODO: Change the autogenerated stub
    }

    public function getConfiguration(array $config, ContainerBuilder $container)
    {

        return parent::getConfiguration($config, $container); // TODO: Change the autogenerated stub
    }

    /**
     * @param array $configs
     * @param ContainerBuilder $container
     * @throws \Exception
     */
    public function load(array $configs, ContainerBuilder $container)
    {
        $configuration = new Configuration();
        $config = $this->processConfiguration($configuration, $configs);

        $loader = new XmlFileLoader(
            $container,
            new FileLocator(__DIR__.'/../Resources/config')
        );
        $loader->load('services.xml');
        //$loader->load('config.xml');
    }
}
